### ISSUE TITLE
Add 'where' Dataview Syntax

### ISSUE THREAD

**Issue by Bluemoondragon07** [tokenshift/obsidian-page-gallery#23]
It's kind of difficult to filter out certain pages without the `where` command in the dataview plug-in. For example, for one page gallery block I've tried:
```
where: 'file.folder = this.file.folder and file.name != this.file.name'
```
I want to list all the files in the current folder except for the active file. I can still do it with the page gallery if I specify the folder in `from:` and add a `#hidden` tag to the current note and exclude `#hidden` in the page gallery block. But it'd be more convenient to just use a `where` command.

**Comment by tokenshift** [comment]
Release 0.4.1 now has support for a `where` clause in the gallery config.
