### ISSUE TITLE
[Bug] Parameters not included in Fields Showing Up as Fields

### ISSUE THREAD

**Issue by Bluemoondragon07** [tokenshift/obsidian-page-gallery#29]
Hi. I noticed that due to a recent update values other than those in `fields:`, such as values in `from:`,`groupBy:`, and `sortBy:`, show up as fields in the generated page gallery.

# `From:` Field
![Screenshot 2023-02-26 142845](https://user-images.githubusercontent.com/121056178/221435600-5f659611-6dcd-456a-926c-3f2cf02f0c69.png)
![Screenshot 2023-02-26 142820](https://user-images.githubusercontent.com/121056178/221435602-64718071-855c-47b4-bdc7-a2a7a063deda.png)
The only field that is expected to appear is the file name, but the file path appears as well.

# `sortBy:` Field
![Screenshot 2023-02-26 142933](https://user-images.githubusercontent.com/121056178/221435699-b1c33fbc-b33f-4b24-89c9-53834f3e538b.png)
![Screenshot 2023-02-26 142908](https://user-images.githubusercontent.com/121056178/221435703-b5b4f58d-a60e-44aa-bf53-773c61b1af20.png)
Here again, the only expected field is the file name. The file path does not show anymore, but is instead replaced by the values that the notes are being sorted by.

# `groupBy:` Field
![Screenshot 2023-02-26 143121](https://user-images.githubusercontent.com/121056178/221435781-d9a0c1eb-9849-4199-8838-17a083636b02.png)
![Screenshot 2023-02-26 143104](https://user-images.githubusercontent.com/121056178/221435785-30cc4163-d539-463e-8be9-8804c30faf44.png)
Here, I want to show the file name, sort the files by creation date, and group them by the subfolder they are in, rendered as a link. This all works, but now both the `sortBy` and `groupBy` values are both showing up as their own fields *on* each page gallery tile as well. 

***

It seems like after the update other fields show up on the page gallery tiles rather than just those specified in the `fields:` field.

**Comment by tokenshift** [comment]
Thank you for the bug report! This should be fixed now in v0.4.2.
