### ISSUE TITLE
Find multiple images from single file

### ISSUE THREAD

**Issue by ethanmiller1** [tokenshift/obsidian-page-gallery#36]
I have [a file](https://github.com/ethanimproving/Family-Ideas/blob/master/Shopping/House%20Ideas/House%20Rennovation%20Ideas.md) that displays multiple images uploaded to Imgur. Is it possible to add support for the gallery displaying multiple gallery items from a single file? It could be based on headings, or each image could be prefixed with `image:: [my-image](example)`.

**Comment by tokenshift** [comment]
This wouldn't work well with other page-gallery features, like fields & expressions, which are all based on page-level (rather than image-level) metadata. This plugin might be a better fit for what you're trying to do: https://github.com/Darakah/obsidian-gallery
