### ISSUE TITLE
When I use the banner plugin,the page gallary can't find the image

### ISSUE THREAD

**Issue by JettyLee17** [tokenshift/obsidian-page-gallery#48]
When I use the banner plugin,the page gallary can't find the image,why?Can you fix it?

**Comment by JettyLee17** [comment]
it might be obsidian the obsidian version issue, the version is 1.3.4, I delete the upgrade,then it works !!! Now my obsidian version is 1.2.8

**Comment by tokenshift** [comment]
For clarification, page-gallery isn't finding and using the image that you have set as a banner image on the page, or it's not finding any images if you're using the banner plugin at all (under Obsidian 1.3.4)?

**Comment by JettyLee17** [comment]
It is not finding any image when I use the banner plugin in the Obsidian version 1.3.4

**Comment by tokenshift** [comment]
This should now be fixed in v0.7.4.
