### ISSUE TITLE
Reduce annoying reloading with flashing

### ISSUE THREAD

**Issue by Azona77** [tokenshift/obsidian-page-gallery#50]
The plugin will check the content every 2 seconds. 

If any of the items are updated, the gallery page will refresh and flash (when gallery page is in the split window). 
Not sure why this issue is not occuring in the dataview plugin.

Although the reloading process is not a functional issue, it is still somewhat annoying.
Imagine that, as you are typing, the page next to your editing note will flash every 2 seconds.

**Comment by Azona77** [comment]
![image](https://github.com/tokenshift/obsidian-page-gallery/assets/76045875/6a89681d-e650-4639-8d1c-28804a923c4b)
I found this parameter of refreshInterval in the main.js, but simply changing it doesn't work as I thought.
hope adding an option in the future version😉.

**Comment by tokenshift** [comment]
I've reworked the page-gallery refresh logic to avoid redrawing the whole view when pages are updated. This should remove the "flashing" issue without having to increase the interval or disable automatic refreshing entirely.
