### ISSUE TITLE
Page image not showing in preview but showing if you search

### ISSUE THREAD

**Issue by stevenlis** [tokenshift/obsidian-page-gallery#54]
Versions:
- Dataview Version: 0.5.56 (currently installed: 0.5.56)
- Page Gallery Version: 0.7.4 (currently installed: 0.7.4)
- Obsidian Version 1.4.5 (Installer 1.3.5)

```
page-gallery
from: '"Data Visualization/Examples"'
orientation: landscape
columns: 10
gutterSize: 5px
height: 100px
position: top
filter: true
radius: 1px
size: cover
fields: []
```

<img width="810" alt="CS-StEUjDbT@2x" src="https://github.com/tokenshift/obsidian-page-gallery/assets/33796896/0dc51ccf-cce1-4dd0-9c7a-106a0912cffe">

![CS-KhMZ6c8S@2x](https://github.com/tokenshift/obsidian-page-gallery/assets/33796896/cd76991a-1679-4111-acce-7368c2f08843)

**Comment by tokenshift** [comment]
I suspect you're running into the default `limit` (100); to keep Obsidian from crashing on devices with limited memory, page-gallery will only load the first 100 matching results by default. You can set `limit` to something higher (or `null`) to see everything. See the list of options in https://github.com/tokenshift/obsidian-page-gallery/blob/main/README.md.

**Comment by stevenlis** [comment]
@tokenshift  Thanks, I do think that might be the reason.
