### ISSUE TITLE
Does width and height really work?

### ISSUE THREAD

**Issue by Cammagno** [tokenshift/obsidian-page-gallery#62]
This does not seem to work for me, or I misunderstand as it's supposed to work (according to what is written in the Readme table).

If I have an explicit column value, followed by an explicit width value (whichever), the second is ignored, and the shown width is calculated based on the columns number.
Even if I don't have an explicit column value and I have an explicit width value (whichever), it is ignored, and the shown width is calculated based on the default columns number of 4.

Also height seems to be totally ignored for me: whichever value I set, it's ignored.
BTW, in the Readme it says that the default height is calculated according to "imageWidth"... is this different from the "width" described in the above row of the table there?

Probably I'm doing something wrong, or I don't get how it's supposed to work...

**Comment by tokenshift** [comment]
The `width` and `height` settings were broken in a previous release; that's been fixed in 0.8.3. I've updated the README to clarify what the different options are.
