### ISSUE TITLE
No longer works in Obsidian Desktop Version 1.5.12

### ISSUE THREAD

**Issue by jack2game** [tokenshift/obsidian-page-gallery#68]
It appears that this add on stopped working... do you mind fixing it?

This is a crucial part of my daily note. Thanks.

**Comment by tokenshift** [comment]
I'm currently using page-gallery 0.8.4 on Obsidian 1.5.12 on both Mac and Windows without any issues. Can you confirm what error messages you're seeing, if any, what version of obsidian-dataview you're using, and post a sample page-gallery code block that isn't working for you?

**Comment by jack2game** [comment]
Thanks for looking into this. I think the issue was caused by my dataview not running correctly. I reinstalled dataview and everything works fine now. Will close this issue.
