### ISSUE TITLE
Importing a Specific Folder Path

### ISSUE THREAD

**Issue by leelax22** [tokenshift/obsidian-page-gallery#72]
Of course, it should be done, but strangely, it didn't work, so I'm posting it.

I tried to get the notes in the folder by typing `from "folder path"` as if I was querying it in the database, but I couldn't get anything.

Is this function not implemented by any chance?

**Comment by tokenshift** [comment]
The `from` option works. The config is in YAML format; see the example here: https://github.com/tokenshift/obsidian-page-gallery?tab=readme-ov-file#usage

For your example, you'd use something like:

```yaml
from: '"folder path"'
```

**Comment by leelax22** [comment]
Thank you. I understood the confusion.
`from: '"Images" AND #yosemite'`
I thought you were using `''` because of the AND option.
However, `''` is also required when applying only the folder path.
It works. Thank you!
